application:
  allow-credentials: true
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - Access-Control-Expose-Headers
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
    - X-total-count
  exposed-headers:
    - X-Xsrf-Token
    - X-total-count
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: 123456
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
jwt:
  header: Authorization
  secret: 0mgWGti7CYzmbzWL4xWQ
  expiration: 604800